### ISSUE TITLE
App\Models\User::activeSubscriptions must return a relationship instance.

### ISSUE THREAD

**Issue by sajjad-talebi** [bpuig/laravel-subby#146]
When I want to check the user's active subscription with this method
I am facing the following problem

$user->activeSubscriptions

[link](https://flareapp.io/share/pPvOyRn7)

If I apply with this method, it works correctly
$user->activeSubscriptions()

Can a user have multiple active subscriptions?
If the answer is negative, this method should return boolean

Thanks for your nice package

**Comment by bpuig** [comment]
In theory, it can. Since this package was orginally forked, maybe some things don't work as expected. I'll take a look

**Comment by rehmankhalil1001** [comment]
getting this error, using laravel 10 with laravel-subby v7.0

LogicException: App\Models\User::activeSubscriptions must return a relationship instance. in file /Users/apple/Desktop/php/convertpods-latest/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 583

#0 /Users/apple/Desktop/php/convertpods-latest/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(526): Illuminate\Database\Eloquent\Model-&gt;getRelationshipFromMethod(&#039;activeSubscript...&#039;)
#1 /Users/apple/Desktop/php/convertpods-latest/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(451): Illuminate\Database\Eloquent\Model-&gt;getRelationValue(&#039;activeSubscript...&#039;)
#2 /Users/apple/Desktop/php/convertpods-latest/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2227): Illuminate\Database\Eloquent\Model-&gt;getAttribute(&#039;activeSubscript...&#039;)
#3 /Users/apple/Desktop/php/convertpods-latest/app/Http/Controllers/UserController.php(243): Illuminate\Database\Eloquent\Model-&gt;__get(&#039;activeSubscript...&#039;)


Any luck on resolving this?
